config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nodes
  root to: 'nodes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_ancestry

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, except: %I[new create index]
  before_action :authenticate_user!, except: %I[index show]

  def index
    @nodes = Node.all
  end

  def show; end

  def new
    @node = Node.new(parent_id: params[:parent_id])
    # @node.image = params[:file]
  end

  def create
    @node = Node.new(node_params)
    if @node.save
      redirect_to nodes_path, notice: 'A new node was successfully saved'
    else
      flash[:alert] = 'An error occurred while saving new node'
      render :new
    end
  end

  def edit; end

  def update
    if @node.update node_params
      redirect_to nodes_path, notice: 'The node was successfully updated'
    else
      flash[:alert] = 'An error occurred while updating node'
      render :edit
    end
  end

  def destroy
    @node.destroy
    if @node.destroyed?
      flash[:notice] = 'The node was successfully deleted'
    else
      flash[:alert] = 'An error occurred while deleting node'
    end
    redirect_to nodes_path
  end

  private

  def node_params
    params.require(:node).permit(:title, :description, :image, :parent_id, :remove_image)
  end

  def set_node
    @node = Node.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
  def nested_nodes(nodes, sub = false)
    color = 'list-group-item list-group-item-'
    color += sub ? 'secondary' : 'primary'
    nodes.map do |node, sub_nodes|
      if !sub_nodes.empty?
        content_tag(:div,
                    render(partial: 'nodes/node',
                           locals: { node: node, color: color }) +
                        render(partial: 'nodes/sub_nodes',
                               locals: { sub_nodes: sub_nodes, collapse_id: node.id }),
                    class: 'node')
      else
        content_tag(:div,
                    render(partial: 'nodes/node', locals: { node: node, color: color }),
                    class: 'node')
      end
    end.join.html_safe
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rubricator
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    - if notice
      .alert.alert-primary.alert-dismissible.fade.show{ role: "alert" }
        = notice
        %button.close{ type:"button", "data-dismiss":"alert", "aria-label":"Close" }
          %span{ "aria-hidden":"true" } x
    - if alert
      .alert.alert-danger.alert-dismissible.fade.show{ role:"alert" }
        = alert
        %button.close{ type:"button", "data-dismiss":"alert", "aria-label":"Close" }
          %span{ "aria-hidden":"true" } x
    %nav.navbar.navbar-dark.bg-dark
      = link_to 'Nodes List', root_path, class: 'navbar-brand'
      - if user_signed_in?
        = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'navbar-brand'
      - else
        = link_to 'Sign In', new_user_session_path, class: 'navbar-brand'
    .container
      = yield

app/views/nodes/_form.html.haml
= simple_form_for @node do |f|
  = f.hidden_field :parent_id
  = f.input :title
  = f.input :description, rows: 8
  = f.file_field :image

  = yield(f) if block_given?

  %br
  = f.button :submit

app/views/nodes/_node.html.haml
-#%div{class:"list-group-item list-group-item-action flex-column align-items-start"}
-#= link_to node.title, node_path(node), class: 'list-group-item list-group-item-action flex-column align-items-start' do
-#flex-column align-items-start
%a{ href: node_path(node), class: color }
  .d-flex.w-100.justify-content-between
    %h5.mb-1 #{ node.title }
    %small #{ image_tag(node.image.url(:thumb)) if node.image? }
  %p.mb-1 #{ (node.description?) ? node.description : 'Description is empty' }
- if user_signed_in?
  .list-group-item#action-btn
    = link_to 'Add Children', new_node_path(parent_id: node), class: 'btn btn-primary btn-sm'
    = link_to 'Edit', edit_node_path(node), class: 'btn btn-warning btn-sm'
    = link_to 'Delete', node_path(node), method: :delete, data: { confirm: 'Sure?' }, class: 'btn btn-danger btn-sm'

app/views/nodes/_sub_nodes.html.haml
.list-group
  %button.btn.btn-secondary{ "data-toggle":"collapse", "data-target":"#collapse_id" + collapse_id.to_s, "aria-expanded":"false", "aria-controls":'#collapse_id' + collapse_id.to_s} Show child
  %div.collapse.multi-collapse{ id: 'collapse_id' + collapse_id.to_s }
    = nested_nodes(sub_nodes, sub:true)

app/views/nodes/edit.html.haml
= render 'form' do |f|
  - if @node.image?
    %br
    = f.label 'Remove image?'
    = f.check_box :remove_image

app/views/nodes/index.html.haml
.list-group
  - if user_signed_in?
    = link_to 'Create New Node', new_node_path, class: 'btn btn-success', id: 'new-node-btn'
  = nested_nodes @nodes.arrange(order: :created_at)

app/views/nodes/new.html.haml
= render 'form'

app/views/nodes/show.html.haml
.row
  .col-md-8.align-self-center
    .node-data
      .row
        %h1.col-lg #{ @node.title }
      .row
        %h3.col-lg #{ (@node.description?) ? @node.description : 'Description is empty' }
  .col-md-4.align-self-center
    = image_tag(@node.image.url(:large)) if @node.image?